name: Build Executables for All Platforms

on:
  push:
    tags:
      - 'V*'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller numpy

      - name: Build Windows executable
        run: |
          pyinstaller --onefile --hidden-import=numpy --collect-submodules numpy --collect-all numpy unsuper.py
          mv dist/unsuper.exe dist/unsuper_windows.exe

      - name: Upload Windows binary
        uses: softprops/action-gh-release@v1
        with:
          files: dist/unsuper_windows.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller numpy

      - name: Build Linux executable
        run: |
          pyinstaller --onefile --hidden-import=numpy --collect-submodules numpy --collect-all numpy unsuper.py
          mv dist/unsuper dist/unsuper_linux

      - name: Upload Linux binary
        uses: softprops/action-gh-release@v1
        with:
          files: dist/unsuper_linux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller numpy

      - name: Build macOS executable
        run: |
          pyinstaller --onefile --hidden-import=numpy --collect-submodules numpy --collect-all numpy unsuper.py
          mv dist/unsuper dist/unsuper_macos

      - name: Upload macOS binary
        uses: softprops/action-gh-release@v1
        with:
          files: dist/unsuper_macos
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
